// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftzacpsokrmbgpnynmoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0emFjcHNva3JtYmdwbnlubW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDEwMjEsImV4cCI6MjA3MzIxNzAyMX0.EssNsM2u29JMkY5ty5WlXK8jrv8aoJj3LSlZXvoB70o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});