name: Deploy Supabase Functions

on:
  push:
    branches:
      - main  # deploy only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o supabase.tar.gz
          mkdir cli_tmp
          tar -xzf supabase.tar.gz -C cli_tmp
          chmod +x cli_tmp/supabase
          sudo mv cli_tmp/supabase /usr/local/bin/supabase

      - name: Check Supabase CLI version
        run: supabase --version

      - name: Deploy ai-recommendations function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase functions deploy ai-recommendations \
            --project-
